Fletnix/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'
urlpatterns = [
    path('register/',views.register, name = 'register'),
    path('login/',views.login, name = 'login'),
    path('detail/', views.profile_detail, name = 'profile_detail'),
    path('update/', views.profile_update, name = 'profile_update'),
    path('logout/', views.logout, name = 'logout')
]

Fletnix/apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('add/', views.profile_add, name = 'add'),
    path('edit/<int:pk>/', views.profiles_edit, name = 'edit'),
    path('switchuser/<int:pk>/', views.who_is_watching, name = 'switcher')
]

Fletnix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('Fletnix.apps.movies.urls')),
    path('core/', include('Fletnix.apps.core.urls')),
    path('accounts/', include('Fletnix.apps.accounts.urls')),
    path('profiles/', include('Fletnix.apps.profiles.urls')),
    path('api/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fletnix/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    ENGLISH = '?language=en-US'
    PORTUGUES = '?language=pt-BR'
    USER_LANGUAGE_CHOICE = [
        (ENGLISH, 'English'),
        (PORTUGUES, 'Portugues')
    ]

    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    user_language = models.CharField(max_length=30, choices=USER_LANGUAGE_CHOICE, default=ENGLISH)
    

    def __str__(self):
        return str(self.user)

Fletnix/apps/accounts/forms.py
from django import forms
from . models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'

Fletnix/apps/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.core.validators import validate_email
from Fletnix.apps.accounts.models import UserProfile
from .forms import UserProfileForm

def register(request):
    if request.user.is_authenticated:
        # return redirect('accounts:detail')
        print('esta autenticado')
    if request.method !='POST':
        return render(request, 'register.html')

    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')
    confirm_password = request.POST.get('confirm_password')

    if not first_name and not last_name and not username and not email and not password and not confirm_password:
        messages.error(request, 'All fields must be filled')
        return render(request, 'register.html')

    if password != confirm_password:
        messages.error(request, 'Password does not match')
        return render(request, 'register.html')

    if len(password) < 5:
        messages.error(request, 'Password must have 6 characters at least')
        return render(request, 'register.html')

    if len(username) < 4:
        messages.error(request, 'Username must have 5 characters at least')
        return render(request, 'register.html')
    
    if User.objects.filter(username=username).exists():
        messages.error(request, 'This username has been taken already')
        return render(request, 'register.html')	

    if User.objects.filter(email=email).exists():
        messages.error(request, 'This e-mail address has been taken already')
        return render(request, 'register.html')
    try:
        validate_email(email)
    except:
        messages.error(request, 'Invalid Email')
        return render(request, 'register.html')
        
def login(request):
    if request.user.is_authenticated:
        print('esta autenticado')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username = username, password = password)

        if not user:
            messages.error(request, 'User name or password incorrect')
            return render(request, 'login.html')
        else:
            auth.login(request, user)
            messages.success(request, f'Hello {request.user.first_name} welcome back! :)')
            return redirect('movies:index')
    return render(request, 'login.html')

def register(request):
    if request.user.is_authenticated:
        print('esta autenticado')
    if request.method != 'POST':
        return render(request, 'register.html')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    username = request.POST.get('username')
    email = request.POST.get('email')
    password = request.POST.get('password')
    confirm_password = request.POST.get('confirm_password')

    if not first_name and not last_name and not username and not email and not password and not confirm_password:
        messages.error(request, 'All fiels must be completed')
        return render(request, 'register.html')
    
    if password != confirm_password:
        messages.error(request, 'Password does not match')
        return render(request, 'register.html')

    if User.objects.filter(username=username).exists():
        messages.error(request, 'This username has been taken')
        return render(request, 'register.html')

    if User.objects.filter(email = email).exists():
        messages.error(request, 'This email email address has been taken')
        return render(request, 'register.html')

    
    user = User.objects.create_user(username = username, first_name = first_name, last_name = last_name, email = email, password = password)
    user_profile = UserProfile.objects.create(user = user)
    user_profile.save()
    user.save()
    return redirect('user_profile:login')

def logout(request):
    auth.logout(request)
    return redirect('user_profile:login')

def profile_detail(request):
    user = request.user.user_profile
    return render(request, 'user_profile.html', {'user':user})

def profile_update(request):
    profile = request.user.user_profile
    form = UserProfileForm(request.POST or None, instance=profile)
    if request.method == 'POST' and form.is_valid():
        profile.save()
        messages.success(request, 'User settings was updated')
        return redirect('user_profile:profile_detail')

Fletnix/apps/accounts/templates/language_select.html
<div class="modal fade" id="languageSelect" tabindex="-1" role="dialog" aria-labelledby="languageSelectLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg bg-transparent" role="document">
        <div class="modal-content bg-dark text-white">
            <div class="modal-header">
              <h4 class="modal-title font-weight-light" id="ModalCenterTitle"><strong>Language</strong> <span class="text-muted">Settings</span></h4>
              <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
                
            </div>
           
            <div class="modal-body">
                <form action="{% url 'user_profile:profile_update' %}" method="post" id="languageSelectForm">
                    {% csrf_token %}
                    <input type="text" name="user" id="id_user" hidden value="{{request.user.id}}">
                    <div class="row mt-1">
                        <div class="col-12">
                            
                            <select name="user_language" id="id_user_language" class="form-control bg-dark text-white">
                                {% if user.user_language == '?language=en-US' %}
                                <option value="?language=en-US" selected>English</option>
                                <option value="?language=pt-BR">Portugues do Brasil</option>
                                {% else %}
                                <option value="?language=en-US" >English</option>
                                <option value="?language=pt-BR" selected>Portugues</option>
                                {% endif %}
                            </select>
                        </div>
                    </div>
                    
                </form>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-light font-weight-light" onclick="submitlanguageSelectForm()">Save changes</button>
              <button type="button" class="btn btn-outline-light   font-weight-light" data-bs-dismiss="modal">Cancel</button>
              
            </div>
    </div>
    </div>
</div>
<script>
    function submitlanguageSelectForm(){
        document.getElementById("languageSelectForm").submit()  
      }

   

   

</script>

Fletnix/apps/accounts/templates/login.html
{% extends 'base.html' %}


{% block title %}
    Login
{% endblock title %}
    
{% block css %}
    <style>
        body{
            background-image: url(https://bit.ly/2E3scwW);
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            background-color: gray;
            background-blend-mode: multiply;
            width:100vw;
            height:100vh;
        }
        .container-fluid {
            position: relative;
            display:flex;
            align-items:center;
            justify-content:center;
            
            
        }
       .card{
        display: flex;
        width:30em;
        background: rgba(000, 000, 000, 0.75);
        border-radius: 4px;
        flex-direction: column;
        padding: 60px 68px 40px;
       }
       
       
            input{
            width: 100%;
            position: relative;
            z-index: 100;
            background: #333;
            margin-bottom: 20px;
            border-radius: 4px;
            border: none;
            opacity: 1;
            font-size: 1rem;
            color: white;
            line-height: 50px;
            padding: 12px 18px 0;
            }
            
    </style>
{% endblock css %}
    
{% block main %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card ">
                    <div class="card-body bg-transparent text-light ">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="col-12">
                                <div class="row mb-1">
                                    <h2>Sign In</h2>
                                </div>
                                    <div class="row form-floating">
                                        <input type="text" id="id_username" name="username" class="form-control " placeholder="Username" >
                                        <label for="id_username">Username</label>
                                    </div> 
                             
                               
                                    <div class="row form-floating">
                                        <input type="password" id="id_password" name="password" class="form-control ">
                                        <label for="id_password"  class="text-dark">Password</label>
                                    </div> 
                                
                                
                                
                                    
                                <div class="row">
                                    <button class="btn btn-danger btn-lg" style="background-color:#cc5353">Sign In</button>
                                </div> 
                                <div class="row justify-content-between mt-2">
                                    <div class="col"><a href="{% url 'user_profile:register' %}" class="text-decoration-none text-light">Sign up</a></div>
                                    <div class="col"><a href="" class="text-decoration-none text-light">Forgot Passoword</a></div>
                                    
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
{% endblock main %}

Fletnix/apps/accounts/templates/register.html
{% extends 'base.html' %}


{% block title %}
    Register
{% endblock title %}
    
{% block css %}
    <style>
        body{
            background-image: url(https://bit.ly/2E3scwW);
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            background-color: gray;
            background-blend-mode: multiply;
            width:100vw;
            height:100vh;
        }
        .container-fluid {
            position: relative;
            display:flex;
            align-items:center;
            justify-content:center;
            
            
        }
       .card{
        display: flex;
        width:30em;
        background: rgba(000, 000, 000, 0.75);
        border-radius: 4px;
        flex-direction: column;
        padding: 60px 68px 40px;
       }
       
       
            input{
            width: 100%;
            position: relative;
            z-index: 100;
            background: #333;
            margin-bottom: 20px;
            border-radius: 4px;
            border: none;
            opacity: 1;
            font-size: 1rem;
            color: white;
            line-height: 50px;
            padding: 12px 18px 0;
            }
            
    </style>
{% endblock css %}
    
{% block main %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card ">
                    <div class="card-body bg-transparent text-light ">
                        <form action=" " method="post">
                            {% csrf_token %}
                            <div class="col-12">
                                <div class="row mb-1">
                                    <h2>Register</h2>
                                </div>
                                <div class="row form-floating">
                                    <input type="text" id="id_first_name" name="first_name" class="form-control " placeholder="name" >
                                    <label for="id_first_name">First Name</label>
                                </div> 
                             
                               
                                <div class="row form-floating">
                                    <input type="text" id="id_last_name" name="last_name"  class="form-control "  >
                                    <label for="id_last_name" class="text-dark">Last Name</label>
                                </div> 
                                
                                
                                
                                <div class="row form-floating">
                                    <input type="text" id="id_username" name="username" class="form-control "  >
                                    <label for="id_username" class="text-dark">Username</label>
                                </div> 
                               
                                
                               
                                <div class="row form-floating">
                                    <input type="email" id="id_email" name="email" class="form-control "  >
                                    <label for="id_email" class="text-dark">Email</label>
                                </div> 
                               
                                
                                
                                <div class="row form-floating">
                                    <input type="password" id="id_password" name="password" class="form-control "  >
                                    <label for="id_password" class="text-dark">Password</label>
                                </div> 
                                

                                <div class="row form-floating">
                                    <input type="password" id="id_confirm_password" name="confirm_password" class="form-control "  >
                                    <label for="id_confirm_password" class="text-dark">Confirm Password</label>
                                </div>
                                <div class="row">
                                    <button class="btn btn-danger btn-lg" style="background-color:#cc5353">Register</button>
                                </div> 
                                <div class="row justify-content-between mt-2">
                                    <div class="col"><a href="{% url 'user_profile:login' %}" class="text-decoration-none text-light">I have an account</a></div>
                                    <div class="col"><a href="" class="text-decoration-none text-light">Forgot Passoword</a></div>
                                    
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
{% endblock main %}
#TODO salvar imagens em jpeg
#TODO Filtrar conteudo por faixa etaria
#TODO Terminar Register
#TODO Criar Login view e template

Fletnix/apps/accounts/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <style>
        .card-img-overlay {
    
    position: absolute;
    top: 0%;
    bottom: 0;
    left: 0;
    right: 0;
    height: 100%;
    width: 100%;
    opacity: 0;
    -webkit-transition: all 0.4s ease-in-out 0s;
    -moz-transition: all 0.4s ease-in-out 0s;
    transition: all 0.4s ease-in-out 0s;
    background: rgba(0, 0, 0, 0.8);
  }
  .card{
    transform: scale(1);
    transition:  ease-in-out 0.5s;
    z-index: 1
}


.card:hover .card-img-overlay {
    
    opacity: 1;
    transition:  ease-in-out 0.5s;
    
  }
.card-img-overlay:hover{
    z-index: 2;
    transition:  ease-in-out 0.5s;
}
    </style>
{% endblock css %}
    
{% block main %}
    <div class="container-fluid mt-5 mb-auto">

        <div class="row justify-content-center mt-2">
            
            {% if request.user.user_profile.profiles.count <= 3 %}
            <div class="col-2 text-center mb-3 mt-3">
                <button class="btn bg-white" data-bs-toggle="modal" data-bs-target="#profileAdd">New Profile</button>
            </div>
            {% endif %}
                
            
           
            <h1 class="text-white text-center mb-3">Manage Profiles:</h1>
            <div class="col-8">
                <div class="row">
                    {% for obj in request.user.user_profile.profiles.all  %}
            <div class="col-lg-3 col-md-12">
                <div class="card" >
                    <!-- testando avatars para profiles -->
                    
                    {% if obj.user_avatar == 'avatar1' %}
                    <img src="{%static 'img/avatar1.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar2' %}
                    <img src="{%static 'img/avatar2.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar3' %}
                    <img src="{%static 'img/avatar3.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar4' %}
                    <img src="{%static 'img/avatar4.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar5' %}
                    <img src="{%static 'img/avatar5.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar6' %}
                    <img src="{%static 'img/avatar6.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar7' %}
                    <img src="{%static 'img/avatar7.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar8' %}
                    <img src="{%static 'img/avatar8.png'%}" class="card-img-top" height="150" alt="...">
                    {% elif obj.user_avatar == 'avatar9' %}
                    <img src="{%static 'img/avatar9.png'%}" class="card-img-top" height="150" alt="...">
                    {% endif %}
                        
                    
                    <a href="{% url 'profiles:edit' obj.id %}" class="text-decoration-none">
                        <div class="card-img-overlay">
                          
                            <p class="card-text text-white text-center  mt-5 mb-auto"><i class="fas fa-pen-alt"></i></p>
                            <p class="card-text text-white text-center  mb-auto">Edit</p>
                            
                        </div>
                    </a>
                  </div>
                  <p class="text-white text-center mt-2 fs-5">{{obj.user_name|title}}</p>
            </div>
            
            {% endfor %}
                </div>
            
            </div>
        </div>
   
    </div>

    {% include 'profile_add.html' %}
{% endblock main %}