Fletnix/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'
urlpatterns = [
    path('register/',views.register, name = 'register'),
    path('login/',views.login, name = 'login'),
    path('detail/', views.profile_detail, name = 'profile_detail'),
    path('update/', views.profile_update, name = 'profile_update'),
    path('logout/', views.logout, name = 'logout')
]

Fletnix/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('cover/<int:pk>',views.cover, name = 'cover'),
    
]

Fletnix/apps/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieIndexView.as_view(), name = 'index'),
    path('library/movie/', views.MovieSearchView.as_view(), name = 'library_search'),
    path('searcher/', views.movie_searcher, name = 'searcher'),
    path('movie/info/<int:pk>/', views.movie_info, name = 'info'),
    path('new/',views.movie_add, name = 'add'),
    path('library/movie/<int:pk>/', views.movie_detail, name = 'detail'),

    path('save_title/',views.save_titles),
    path('scrape_server/',views.scrape_from_server),

    path('api/movies/', views.MoviesAddApiView.as_view(), name='list_api_view'),
    path('api/movies/<int:pk>/', views.MovieUpdateApiView.as_view(), name='movie_update_view'),
   
    
]

Fletnix/apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('add/', views.profile_add, name = 'add'),
    path('edit/<int:pk>/', views.profiles_edit, name = 'edit'),
    path('switchuser/<int:pk>/', views.who_is_watching, name = 'switcher')
]

Fletnix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('Fletnix.apps.movies.urls')),
    path('core/', include('Fletnix.apps.core.urls')),
    path('accounts/', include('Fletnix.apps.accounts.urls')),
    path('profiles/', include('Fletnix.apps.profiles.urls')),
    path('api/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fletnix/apps/core/models.py
from django.db import models

# Create your models here.

Fletnix/apps/core/views.py
from django.shortcuts import render
from . imdb import search_imdb, get_cover


lista = []

def index(request):
    search = ''
    dicionario = dict()
    global lista
    lista = []
    if request.method =='POST':
        search = request.POST.get('search')
    res = search_imdb(search)
    for item in res:
        dicionario = {'link':item.a.get('href'), 'text':item.text}
        lista.append(dicionario)
    return render(request, 'index.html', {'res':lista})


def cover(request,pk):
    global lista
    res = lista[pk -1]
    movie = get_cover(f"https://www.imdb.com/{res.get('link')}")
    return render(request, 'cover.html',{'res':movie})

Fletnix/core/views.py
from django.shortcuts import render,redirect, reverse
from . imdb import search_imdb, get_cover


lista = []

def index(request):
    search = ''
    dicionario = dict()
    global lista
    lista = []
    if request.method =='POST':
        search = request.POST.get('search')
    res = search_imdb(search)
    for item in res:
        dicionario = {'link':item.a.get('href'), 'text':item.text}
        lista.append(dicionario)
    return render(request, 'index.html', {'res':lista})


def cover(request,pk):
    global lista
    res = lista[pk -1]
    movie = get_cover(f"https://www.imdb.com/{res.get('link')}")
    return render(request, 'cover.html',{'res':movie})

Fletnix/apps/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css">
<link href="{%static 'lightbox/lightbox.min.css'%}" rel="stylesheet">
<link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="{%static 'css/styles.css'%}">
<link rel="stylesheet" href="{%static 'css/image-picker.css'%}">

<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
<script src="{%static '/js/vue.min.js'%}"></script>
<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
<script src="https://unpkg.com/axios@0.20.0-0/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/videojs-playlist.js'%}"></script>
<script src="https://vjs.zencdn.net/7.7.5/video.js"></script>
<script src="{%static 'js/image-picker.min.js'%}"></script>
<script src="https://players.brightcove.net/1507807800001/SJLNAJye7_default/index.min.js"></script>

<title>Fletnix | {%block title%}{%endblock title%}</title>
{% block css %} 
{% endblock css %}
</head>
<body style="background-color: #141414 ;">
    <nav class="navbar navbar-expand-lg navbar-dark  sticky-top" style="background-color:rgba(0,0,0,0.3)">
      <div class="container-fluid">
        <a class="navbar-brand" style="color:#cc5353" href="{% url 'movies:index' %}"> <img style="height:35px;width: 100px;"src="{%static 'img/logo.png'%}" alt=""> </a>
       
        
        {% if not 'register' or not 'login' in request.path or not request.user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'movies:index' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownCategories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu p-0 bg-dark bg-gradient" aria-labelledby="navbarDropdownCategories">
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=action">Action</a></li>
                <li><a class="dropdown-item  bg-transparent text-light" href="{%url 'movies:library_search'%}?search=adventure">Adventure</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=animation">Animation</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=comedy">Comedy</a></li>
                <li><a class="dropdown-item  bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=documentary">Documentary</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=drama">Drama</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=family">Family</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=fantasy">Fantasy</a></li>
                <li><a class="dropdown-item bg-transparent  text-light" href="{%url 'movies:library_search'%}?search=romance">Romance</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownActions" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
              </a>
              <ul class="dropdown-menu p-0 bg-dark bg-gradient" aria-labelledby="navbarDropdownActions">
                <li><a class="dropdown-item  bg-transparent text-light" href="{% url 'movies:searcher' %}">Add a new movie to library</a></li>
              </ul>
            </li>
            
          </ul>
          <form class="d-flex mr-3" method="GET" action="{% url 'movies:library_search' %}">
            <input id="movie-scraper" class="form-control mr-e text-white"  type="search" style="background-color:#18191c;"
            name="search" autocomplete="off" placeholder="Search" aria-label="Search"><span><i  id="search-icon" class="fa fa-search mr-2 fa-2x" ></i></span>
          </form>
          <ul class="navbar-nav ml-3">
            <li class="nav-item ">
             
              <a href="" class=" nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">         
              {% for obj in request.user.user_profile.profiles.all  %}
              
              {% if not obj %}
                {{teste}}
              {% endif %}
                
                {% if obj.profile_watching.first  %}
                {% if obj.user_avatar == 'avatar1' %}
                <img src="{%static 'img/avatar1.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar2' %}
                <img src="{%static 'img/avatar2.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar3' %}
                <img src="{%static 'img/avatar3.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar4' %}
                <img src="{%static 'img/avatar4.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar5' %}
                <img src="{%static 'img/avatar5.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar6' %}
                <img src="{%static 'img/avatar6.png'%}" class="card-img-top" style="width: 30px;"   alt="...">
                {% elif obj.user_avatar == 'avatar7' %}
                <img src="{%static 'img/avatar7.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar8' %}
                <img src="{%static 'img/avatar8.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% elif obj.user_avatar == 'avatar9' %}
                <img src="{%static 'img/avatar9.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                {% endif %} 
                {% endif %} 
              {% endfor %}
              </a>
            
              <ul class="dropdown-menu dropdown-menu-end bg-dark">
                
                {% for obj in request.user.user_profile.profiles.all  %}
                
                {% if not obj.profile_watching.first%}
               
                <li><a class="dropdown-item text-light bg-transparent" href="{% url 'profiles:switcher' obj.id %}"><img src="" alt=""> {% if obj.user_avatar == 'avatar1' %}
                  <img src="{%static 'img/avatar1.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar2' %}
                  <img src="{%static 'img/avatar2.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar3' %}
                  <img src="{%static 'img/avatar3.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar4' %}
                  <img src="{%static 'img/avatar4.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar5' %}
                  <img src="{%static 'img/avatar5.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar6' %}
                  <img src="{%static 'img/avatar6.png'%}" class="card-img-top" style="width: 30px;"   alt="...">
                  {% elif obj.user_avatar == 'avatar7' %}
                  <img src="{%static 'img/avatar7.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar8' %}
                  <img src="{%static 'img/avatar8.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% elif obj.user_avatar == 'avatar9' %}
                  <img src="{%static 'img/avatar9.png'%}" class="card-img-top" style="width: 30px;"  alt="...">
                  {% endif %} {{obj}}</a></li>
                {% endif %}
                  
                
                {% endfor %}
                <div class="dropdown-divider bg-white"></div>
                <li><a class="dropdown-item text-light bg-transparent" href="{% url 'user_profile:profile_detail' %}">Manage Profiles</a></li>
                <div class="dropdown-divider bg-white"></div>
                <li><a class="dropdown-item text-light bg-transparent" href="" data-bs-toggle="modal" data-bs-target="#languageSelect">Language</a></li>
                <li><a class="dropdown-item text-light bg-transparent" href="{% url 'user_profile:logout' %}" >Leave Fletnix</a></li>
               
              </ul>
            </li>
          </ul>
        </div>
        {% endif %}
          
        
      </div>
    </nav>
    <div class="container-fluid">
      
      {% include 'includes/_messages.html' %}
    </div>
    {% include 'language_select.html' %}
    {% block main %}{% endblock main %}
    {% block js %}{% endblock js %}
    <script>
     $( document ).ready(function() {
      var message = setTimeout(function(){
            $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                    $(".alert").remove();
                });
              }, 5000);//5000=5 seconds
            })

            
  </script>
    </script>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="{%static 'js/fletnix-main.js'%}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/3.0.2/videojs-contrib-hls.js"></script> -->
    <script src="{%static 'assets/dist/js/main.js'%}"></script>
    <script src="{%static 'lightbox/lightbox.min.js'%}"></script>
    
    <!-- <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" /> -->
    
    </body>
    </html>