Fletnix/apps/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('add/', views.profile_add, name = 'add'),
    path('edit/<int:pk>/', views.profiles_edit, name = 'edit'),
    path('switchuser/<int:pk>/', views.who_is_watching, name = 'switcher')
]

Fletnix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('Fletnix.apps.movies.urls')),
    path('core/', include('Fletnix.apps.core.urls')),
    path('accounts/', include('Fletnix.apps.accounts.urls')),
    path('profiles/', include('Fletnix.apps.profiles.urls')),
    path('api/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fletnix/apps/profiles/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from Fletnix.apps.accounts.models import UserProfile

class Profiles(models.Model):

    AVATAR1 = 'avatar1'
    AVATAR2 = 'avatar2'
    AVATAR3 = 'avatar3'
    AVATAR4 = 'avatar4'
    AVATAR5 = 'avatar5'
    AVATAR6 = 'avatar6'
    AVATAR7 = 'avatar7'
    AVATAR8 = 'avatar8'
    AVATAR9 = 'avatar9'

    USER_AVATAR_CHOICE = [
        (AVATAR1, 'avatar1'),
        (AVATAR2, 'avatar2'),
        (AVATAR3, 'avatar3'),
        (AVATAR4, 'avatar4'),
        (AVATAR5, 'avatar5'),
        (AVATAR6, 'avatar6'),
        (AVATAR7, 'avatar7'),
        (AVATAR8, 'avatar8'),
        (AVATAR9, 'avatar9'),
    ]


    ADULT  = '1'
    CHILD = '2'
    USER_RATE_CHOICE = [
        (ADULT, 'Adult'),
        (CHILD, 'Child')
    ]


    MALE = '1'
    FEMALE = '2'
    USER_GENDER_CHOICE =[
        (MALE, 'Male'),
        (FEMALE, 'Female')
        ]

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='profiles')
    user_name = models.CharField(max_length=255, null=True)
    user_age = models.CharField(max_length=1, choices=USER_RATE_CHOICE, default=ADULT)
    user_gender = models.CharField(max_length=1, choices=USER_GENDER_CHOICE, default=MALE)
    user_avatar = models.CharField(max_length=20, choices=USER_AVATAR_CHOICE, default=AVATAR1, null=True)

    def __str__(self):
        return self.user_name


class WhoIsWatching(models.Model):
    person = models.ForeignKey(Profiles, on_delete=models.CASCADE, related_name='profile_watching')
    person_avatar = models.CharField(max_length=50, null=True)
    person_age = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.person)

Fletnix/apps/profiles/forms.py
from django import forms
from .models import Profiles, WhoIsWatching

class ProfilesForm(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = '__all__'

class WhoIsWatchinForm(forms.ModelForm):
    class Meta:
        model = WhoIsWatching
        fields = '__all__'

Fletnix/apps/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from Fletnix.apps.accounts.models import UserProfile
from .models import Profiles, WhoIsWatching
from .forms import ProfilesForm, WhoIsWatchinForm
from django.db.models import Q


def profile_add(request):
    accounts_number = Profiles.objects.filter(Q(user = request.user.user_profile))
    if len(accounts_number) <= 3:
        user = request.user.user_profile.id
        form = ProfilesForm()
        if request.method == 'POST':
            form = ProfilesForm(request.POST or None)
            if form.is_valid():
                data_from_form = Profiles(
                    user = form.cleaned_data['user'],
                    user_name = form.cleaned_data['user_name'],
                    user_age = form.cleaned_data['user_age'],
                    user_gender = form.cleaned_data['user_gender'],
                    user_avatar = form.cleaned_data['user_avatar']
                )
                data_from_form.save()
                messages.success(request, f'A new profile {data_from_form.user_name} was created')
                return redirect('user_profile:profile_detail')
    else:
        messages.error(request, 'Maximum number of profiles reached')
        return redirect('user_profile:profile_detail')

def profiles_edit(request, pk):
    profile = get_object_or_404(Profiles, pk = pk)
    form = ProfilesForm(request.POST or None, instance=profile)
    if request.method == 'POST' and form.is_valid():
        profile.save()
        messages.success(request, f'Profile {profile.user_name} was updated with success')
        return redirect('user_profile:profile_detail')
    return render(request, 'profile_edit.html', {'obj':profile})

def who_is_watching(request, pk):
    profile = get_object_or_404(Profiles, pk = pk)
    obj = WhoIsWatching.objects.all()
    

    if not obj:
        print('nao tem obj vou criar')
        obj = WhoIsWatching.objects.create(person = profile, person_avatar = profile.user_avatar, person_age = profile.user_age)
        return redirect('movies:index')
    else:
        
        obj = WhoIsWatching.objects.first()
        obj.person = profile
        obj.person_avatar = profile.user_avatar
        obj.person_age = profile.user_age
        obj.save()
       
        return redirect('movies:index')

    # Por enquanto somente uma instancia de WhoIsWacthing pode ser criada
    
    

Fletnix/apps/profiles/templates/profile_add.html
{% load static %}


{% block css %}
    <style>
       
    </style>
{% endblock css %}
    
<div class="modal fade" id="profileAdd" tabindex="-1" role="dialog" aria-labelledby="profileAddLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg bg-transparent" role="document">
        <div class="modal-content bg-dark text-white">
            <div class="modal-header">
              <h4 class="modal-title font-weight-light" id="ModalCenterTitle"><strong>Profile</strong> <span class="text-muted">Form</span></h4>
              <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
                
            </div>
            <div class="modal-body">
                <form action="{% url 'profiles:add' %}" method="post" id="profileAddForm">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 ">
                            <div class="form-group mb-3">
                                <label for="id_user_name" class="font-weight-light">Profile Name</label>
                                <input type="text" autofocus class="form-control bg-dark text-white" id="id_user_name"  name="user_name" placeholder="Enter Profile Name">
                                <input type="text" hidden id="id_user"  name="user" value="{{request.user.user_profile.id}}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group mb-3">
                                <label for="id_user_age" class="font-weight-light">Profile type age</label>
                                <select id="id_user_age"  name="user_age" class="form-control bg-dark text-white">
                                    <option value="1">Adult</option>
                                    <option value="2">Child</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group mb-3">
                                <label for="id_user_gender" class="font-weight-light">Profile gender</label>
                                <select id="id_user_gender"  name="user_gender" class="form-control bg-dark text-white">
                                    <option value="1">Male</option>
                                    <option value="2">Female</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group mb-3">
                                <label for="id_user_avatar" class="font-weight-light">Avatar</label>
                                <select id="id_user_avatar"  name="user_avatar" class="form-control bg-dark text-white">
                                    <option data-img-src="{%static 'img/avatar1.png'%}" width="50" value='avatar1'></option>
                                    <option data-img-src="{%static 'img/avatar2.png'%}" value='avatar2'></option>
                                    <option data-img-src="{%static 'img/avatar3.png'%}" value='avatar3'></option>
                                    <option data-img-src="{%static 'img/avatar4.png'%}" value='avatar4'></option>
                                    <option data-img-src="{%static 'img/avatar5.png'%}" value='avatar5'></option>
                                    <option data-img-src="{%static 'img/avatar6.png'%}" value='avatar6'></option>
                                    <option data-img-src="{%static 'img/avatar7.png'%}" value='avatar7'></option>
                                    <option data-img-src="{%static 'img/avatar8.png'%}" value='avatar8'></option>
                                    <option data-img-src="{%static 'img/avatar9.png'%}" value='avatar9'></option>
                                    
                                </select>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-light font-weight-light" onclick="submitprofileAddForm()">Save changes</button>
              <button type="button" class="btn btn-outline-light   font-weight-light" data-bs-dismiss="modal">Cancel</button>
              
            </div>
    </div>
</div>
</div>

<script>
    function submitprofileAddForm(){
        document.getElementById("profileAddForm").submit()  
      }

      
</script>


{% block js %}
    <script>
        $("#id_user_avatar").imagepicker()
    </script>
{% endblock js %}
    

Fletnix/apps/profiles/templates/profile_edit.html
{% extends 'base.html' %}

{% load static %}
{% block main %}
    <div class="container-fluid mt-3">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        
                        <form action="{% url 'profiles:edit' obj.id %}" method="post" id="profileAddForm">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 ">
                                    <div class="form-group mb-3">
                                        <label for="id_user_name" class="font-weight-light">Profile Name</label>
                                        <input type="text" autofocus class="form-control " id="id_user_name"  name="user_name" value="{{obj.user_name}}">
                                        <input type="text" hidden id="id_user"  name="user" value="{{request.user.user_profile.id}}">
                                    </div>
                                </div>
                            </div>
        
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mb-3">
                                        <label for="id_user_age" class="font-weight-light">Profile type age</label>
                                        <select id="id_user_age"  name="user_age" class="form-control ">
                                            
                                            {% if obj.user_age == '1' %}
                                            <option value="1" selected>Adult</option>
                                            <option value="2">Child</option>
                                            {% else %}
                                            <option value="1">Adult</option>
                                            <option value="2" selected>Child</option>
                                            {% endif %}
                                                
                                           
                                        </select>
                                    </div>
                                </div>
                            </div>
        
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mb-3">
                                        <label for="id_user_gender" class="font-weight-light">Profile gender</label>
                                        <select id="id_user_gender"  name="user_gender" class="form-control ">
                                            
                                            {% if obj.user_gender == '1' %}
                                            <option value="1" selected>Male</option>
                                            <option value="2">Female</option>
                                            {% else %}
                                            <option value="1">Male</option>
                                            <option value="2" selected>Female</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                </div>
                            </div>
        
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mb-3">
                                        <label for="id_user_avatar" class="font-weight-light">Avatar</label>
                                        <select id="id_user_avatar"  name="user_avatar" class="form-control ">
                                            <option data-img-src="{%static 'img/avatar1.png'%}" {% if obj.user_avatar == 'avatar1' %}selected{% endif %} value='avatar1'></option>
                                            <option data-img-src="{%static 'img/avatar2.png'%}" {% if obj.user_avatar == 'avatar2' %}selected{% endif %} value='avatar2'></option>
                                            <option data-img-src="{%static 'img/avatar3.png'%}" {% if obj.user_avatar == 'avatar3' %}selected{% endif %} value='avatar3'></option>
                                            <option data-img-src="{%static 'img/avatar4.png'%}" {% if obj.user_avatar == 'avatar4' %}selected{% endif %} value='avatar4'></option>
                                            <option data-img-src="{%static 'img/avatar5.png'%}" {% if obj.user_avatar == 'avatar5' %}selected{% endif %} value='avatar5'></option>
                                            <option data-img-src="{%static 'img/avatar6.png'%}" {% if obj.user_avatar == 'avatar6' %}selected{% endif %} value='avatar6'></option>
                                            <option data-img-src="{%static 'img/avatar7.png'%}" {% if obj.user_avatar == 'avatar7' %}selected{% endif %} value='avatar7'></option>
                                            <option data-img-src="{%static 'img/avatar8.png'%}" {% if obj.user_avatar == 'avatar8' %}selected{% endif %} value='avatar8'></option>
                                            <option data-img-src="{%static 'img/avatar9.png'%}" {% if obj.user_avatar == 'avatar9' %}selected{% endif %} value='avatar9'></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-8 text-center">
                                    <button class="btn btn-outline-secondary" type="submit">Save</button>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

{% block js %}
    <script>
        $("#id_user_avatar").imagepicker()
    </script>
{% endblock js %}