Fletnix/apps/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieIndexView.as_view(), name = 'index'),
    path('library/movie/', views.MovieSearchView.as_view(), name = 'library_search'),
    path('searcher/', views.movie_searcher, name = 'searcher'),
    path('movie/info/<int:pk>/', views.movie_info, name = 'info'),
    path('new/',views.movie_add, name = 'add'),
    path('library/movie/<int:pk>/', views.movie_detail, name = 'detail'),

    path('save_title/',views.save_titles),
    path('scrape_server/',views.scrape_from_server),

    path('api/movies/', views.MoviesAddApiView.as_view(), name='list_api_view'),
    path('api/movies/<int:pk>/', views.MovieUpdateApiView.as_view(), name='movie_update_view'),
   
    
]

Fletnix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('Fletnix.apps.movies.urls')),
    path('core/', include('Fletnix.apps.core.urls')),
    path('accounts/', include('Fletnix.apps.accounts.urls')),
    path('profiles/', include('Fletnix.apps.profiles.urls')),
    path('api/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fletnix/apps/movies/models.py
from django.db import models
from django.contrib.auth.models import User


class Movies(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='movies', null=True, blank=True)
    title = models.CharField(max_length=255, null=True, default='')
    summary = models.TextField(null=True,default='')
    year = models.CharField(max_length=255, null=True,default='')
    trailer = models.TextField(null=True,default='')
    cast = models.TextField(null=True,default='')
    genre = models.CharField(max_length=255, null=True,default='')
    cover = models.TextField(null=True,default='')
    url = models.TextField(null=True,default='')
    image = models.ImageField(upload_to = 'images/', null=True, blank = True)
    relevance = models.CharField(max_length=10, null=True, blank=True)
    certification = models.CharField(max_length=10, null=True, blank=True)

    
    def __str__(self):
        return self.title

Fletnix/apps/movies/forms.py
from django import forms
from .models import Movies

class MoviesForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = '__all__'

Fletnix/apps/movies/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views.generic import ListView
from django.contrib import messages
from django.db.models import Q
from django.core.files import File
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from rest_framework import generics
from django.http import HttpResponse

from Fletnix.apps.core.imdb import search_imdb, get_cover
from Fletnix.apps.profiles.models import WhoIsWatching
from .models import Movies
from .forms import MoviesForm
from .serializers import MoviesSerializer

from bs4 import BeautifulSoup as bs
import requests
from urllib import request as req
from tempfile import NamedTemporaryFile

import json

lista = []

class MoviesAddApiView(generics.ListCreateAPIView):
    queryset = Movies.objects.all()
    serializer_class = MoviesSerializer

class MovieUpdateApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Movies.objects.all()
    serializer_class = MoviesSerializer

@method_decorator(login_required, name = 'dispatch')
class MovieIndexView(ListView):
    model = Movies
    context_object_name = 'movies'
    template_name = 'index_movie.html'
    paginate_by = 12

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user = self.request.user)
        if not qs:
            return qs
        return qs


    def get_context_data(self):
        context = super().get_context_data()
        context['recents'] = Movies.objects.filter(user = self.request.user).order_by('-id')[:7]
        context['watching'] = WhoIsWatching.objects.first()
        return context

class MovieSearchView(MovieIndexView):
    template_name = 'library_movie_search.html'
    paginate_by =  300
    def get_queryset(self):
        search = self.request.GET.get('search')
        qs = super().get_queryset()
        qs = qs.filter(
            Q(title__icontains = search) |
            Q(genre__icontains = search))
        if not search and not qs:
            return qs
        return qs
    
    

def movie_detail(request, pk):
    movie = get_object_or_404(Movies, pk = pk)
    return render(request, 'movie_detail.html', {'obj':movie})

def movie_searcher(request):
    res = ''
    dicionario = dict()
    global lista
    lista = []
    if request.method =='POST':
        search = request.POST.get('search')
        res = search_imdb(search, request.user.user_profile.user_language)
    for item in res:
        # print(item.find("img", class_="poster"))
        sliced = str(item.img).split('"')
        imagem = ''
        if len(sliced) > 1:
            imagem = sliced[7]
        else:
            imagem = None
        
        dicionario = {
            'link':item.a.get('href'), 
            'text':item.h2.text,
            'summary':item.find(class_="overview").text, 
            # 'image':str(item.img)
            'image':f'https://www.themoviedb.org{imagem}'
            }
        
        lista.append(dicionario)
    return render(request, 'search_movie.html', {'res':lista})

def movie_info(request,pk):
    global lista
    res = lista[pk -1]
    movie = get_cover(f"https://www.themoviedb.org{res.get('link')}")
    return render(request, 'movie_info.html',{'res':movie})

def movie_add(request):
    form = MoviesForm()
    if request.method == 'POST':
        form = MoviesForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            data_from_form = Movies(
                user = request.user,
                title = form.cleaned_data['title'],
                summary = form.cleaned_data['summary'],
                year = form.cleaned_data['year'],
                genre = form.cleaned_data['genre'],
                cover = form.cleaned_data['cover'],
                url = form.cleaned_data['url'],
                trailer = form.cleaned_data['trailer'],
                cast = form.cleaned_data['cast'],
                image = form.cleaned_data['image'],
                certification = form.cleaned_data['certification'],
                relevance = form.cleaned_data['relevance']

            )
            if not data_from_form.image:
                striped_image = str(data_from_form.cover).split('/')
                image_url = data_from_form.cover
                img_temp = NamedTemporaryFile(delete = True)
                img_temp.write(req.urlopen(image_url).read())
                img_temp.flush()
                data_from_form.image.save(striped_image[-1], File(img_temp))
            
            data_from_form.genre = data_from_form.genre[0:-1]
            if not "iframe" or not "youtube" in data_from_form.url:
                data_from_form.url = "{sources: [{src:'url' ,type: 'video/mp4'}],poster: 'image'},".replace('url', data_from_form.url).replace('image', data_from_form.image.url)
            data_from_form.user = request.user
            if not data_from_form.trailer:
                data_from_form.trailer = 'https://www.youtube.com/watch?v=trailer'
            if not data_from_form.cast:
                data_from_form.cast = 'Information not available'
            data_from_form.save()
            messages.success(request, f'Yay! "{data_from_form.title}" was added to your library')
            return redirect('movies:index')
        if form.errors:
            print(form.errors)
    return render(request, 'movie_info.html', {'form':form})


def save_titles(request):
    movies = Movies.objects.all()
    movie_list = []
    for movie in movies:
        movie_dict = {"title":movie.title, "url":movie.url}
        movie_list.append(movie_dict)
        # print(f'{movie.title} {movie.url}')
      
    with open('titles_saved.json','w') as file:
        teste = json.dump(movie_list, file)
    return HttpResponse(movies)




###############################################################################################

def search_from_my_server(request, search):

    dicionario = dict()
    global lista
    lista = []
    res = search_imdb(search, request.user.user_profile.user_language)
  
    if len(list(res)) > 0:
        return res
    else:
        movie_less_last = search.strip(".mp4")[:-1]
        last_char = search.strip(".mp4")[-1]
        fixed_name = f'{movie_less_last} {last_char}'
        return search_imdb(fixed_name, request.user.user_profile.user_language)
        



def scrape_from_server(request):
    req = requests.get('http://192.168.1.18/Filmes/')
    soup = bs(req.text, 'html.parser')
    movie_link = soup.find_all('a')
    for link in movie_link:
        if 'href' in link.attrs and  'mp4' in link.attrs['href']:
            res = search_from_my_server(request, link.text.strip('.mp4'))
            item = list(res)
            print(item)
            # sliced = str(list(res).img).split('"')
            # print(sliced)
            
    # print(movie_link)
    return HttpResponse(req)

Fletnix/movies/views.py
from django.shortcuts import render,redirect, reverse
from Fletnix.core.imdb import search_imdb, get_cover
from .models import Movies
from .forms import MoviesForm


lista = []

def movie_index(request):
    movies = Movies.objects.all()
    return render(request, 'index_movie.html', {'movies':movies})


def movie_searcher(request):
    search = ''
    dicionario = dict()
    global lista
    lista = []
    if request.method =='POST':
        search = request.POST.get('search')
    res = search_imdb(search)
    print(res)
    for item in res:
        dicionario = {
            'link':item.a.get('href'), 
            'text':item.h2.text,
            # 'summary':item.p, 
            'summary':item.find(class_="overview").text, 
            'image':str(item.img)
            }
        lista.append(dicionario)
    # print(dicionario)
    return render(request, 'index.html', {'res':lista})

def movie_info(request,pk):
    global lista
    res = lista[pk -1]
    movie = get_cover(f"https://www.themoviedb.org{res.get('link')}")
    return render(request, 'movie_info.html',{'res':movie})


def movie_add(request):
    form = MoviesForm()
    title_t = request.GET.get('title')
    print(title_t)
    if request.method == 'POST':
        form = MoviesForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            data_from_form = Movies(
                title = form.cleaned_data['title'],
                summary = form.cleaned_data['summary'],
                year = form.cleaned_data['year'],
                genre = form.cleaned_data['genre'],
                cover = form.cleaned_data['cover'],
                url = form.cleaned_data['url'],
                trailer = form.cleaned_data['trailer'],
                cast = form.cleaned_data['cast']

            )
            data_from_form.genre = data_from_form.genre[0:-1]
            data_from_form.save()
            return redirect('movies:index')
        else:
            print('form nao foi valido')
    return render(request, 'movie_info.html', {'form':form})





############# Scraping do IMDB ####################


# def movie_searcher(request):
#     search = ''
#     dicionario = dict()
#     global lista
#     lista = []
#     if request.method =='POST':
#         search = request.POST.get('search')
#     res = search_imdb(search)
#     for item in res:
#         dicionario = {'link':item.a.get('href'), 'text':item.text}
#         lista.append(dicionario)
#     return render(request, 'index.html', {'res':lista})


# def movie_info(request,pk):
#     global lista
#     res = lista[pk -1]
#     movie = get_cover(f"https://www.imdb.com/{res.get('link')}")
#     return render(request, 'search_movie.html',{'res':movie})

Fletnix/apps/movies/templates/index_movie.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Library{% endblock title %}
{% block css %}
<link href="{%static 'lightbox/lightbox.css'%}" rel="stylesheet">

<style>
    img {
    box-shadow: 1px 1px 5px 1px rgba(0, 0, 0, 0.1);
    border-radius: 5px
}

.card-image {
  position: relative;
}
.card-img-overlay {
    
    position: absolute;
    top: 0%;
    bottom: 0;
    left: 0;
    right: 0;
    height: 100%;
    width: 100%;
    opacity: 0;
    -webkit-transition: all 0.4s ease-in-out 0s;
    -moz-transition: all 0.4s ease-in-out 0s;
    transition: all 0.4s ease-in-out 0s;
    background: rgba(0, 0, 0, 0.8);
  }
.card{
    transform: scale(1);
    transition:  ease-in-out 0.5s;
    z-index: 1
}

.card:hover{
    transform: scale(1.1);
    z-index:2;
    transition:  ease-in-out 0.5s;
  }
.card:hover .card-img-overlay {
    
    opacity: 1;
    transition:  ease-in-out 0.5s;
    
  }
.card-img-overlay:hover{
    z-index: 2;
    transition:  ease-in-out 0.5s;
}

</style>
{% endblock css %}
{% block main %}



<div class="container-fluid">
  <h3 class=" text-white">Recently added</h3>
  <div class="col">
    <div class="row">
      <div class="gallery js-flickity" data-flickity-options='{ "freeScroll": true, "wrapAround": true }'>
        {% for movie in recents %}
        
       
        <div class="gallery-cell">
          <a href="{%url 'movies:detail' movie.id%}"><img src="{{movie.cover}}" alt="">
            <div class="carousel-caption d-none d-md-block d-sm-block" style="background-color:rgba(0,0,0,0.8);">
              <h5> <strong>{{movie.title}}</strong> </h5>
            </div></a>
        </div>
       
          
       
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<div class="container-fluid mt-5 ">
  <h3 class=" text-white">Your Library</h3>
    <div class="col-xl-12 col ">
        <div class="row ">
            {% for movie in movies %}
            <div class="d-flex justify-content-center col-xl-2 col-sm-6 mt-2 align-items-center">
                <div class="card" style="width: 18rem;border: none;">
                    <img src="{{movie.cover}}" style="max-width:238; max-height:350"class="card-img-top" alt="...">
                        <div class="card-img-overlay align-middle text-wrap text-center" >
                            <h5 class="text-light"> <strong>{{movie.title}}</strong> </h5>
                            
                            {% if movie.summary|length > 200 %}
                            <p class="text-light" >{{movie.summary|slice:"0:200"}}...</p>
                            {% else %}
                            <p class="text-light" >{{movie.summary}}</p>
                            {% endif %}
                              
                            
                            <div class="row align-text-bottom">
                                <div class="col-6">
                                    <a href="{% url 'movies:detail' movie.id %}" style="border:2px white solid; border-radius:1px" class="text-center btn text-decoration-none text-white p-4"> Go to Movie<span style="font-size:20px"><i  class="large material-icons text-danger" aria-hidden="true">play_circle_outline</i></span>
                                    </a>
                                </div>
                                <div class="col-6">
                                    <a href="https://www.youtube.com/watch?v={{movie.trailer}}" data-lightbox style="border:2px white solid; border-radius:1px"  class="text-center btn text-decoration-none text-white p-4">Watch trailer <span><i class="large material-icons text-danger" aria-hidden="true">play_circle_filled</i></span>
                                    </a>
                                </div>
                            </div>
                      </div>
                    <div class="card-body text-center bg-dark text-white">
                      <h5 class="card-title" style="font-size:1em">{{movie.title}}</h5>
                      <p style="font-size: 0.8em;" class="text-muted text-truncate">{{movie.genre}}</p>
                    </div>
                  </div>
            </div>
            {% endfor %}     
        </div>
    </div>
</div>
<div class="container mt-3">
  <div class="flex-row">
    <div class="d-flex justify-content-center">
      {%include 'includes/_pagination.html'%}
    </div>
  </div>   
</div>
<footer class="footer mt-auto py-3  bg-dark text-center ">
  <div class="container">
    <img style="height:35px;width: 100px;"src="{%static 'img/logo.png'%}" alt="">
    <p class=" text-light">{%now 'Y'%}</p>
    <p class=" text-light">All the information scraped from</p>
    <a href="https://www.themoviedb.org/"><img src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg" style="width:250px" alt=""></a>
  </div>
</footer>
{% endblock main %}

Fletnix/apps/movies/templates/library_movie_search.html
{% extends 'index_movie.html' %}

Fletnix/apps/movies/templates/movie_detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

<style>
    .card{
        background-color: rgba(0,0,0,0.5);
    }
    body{
     
      
      background-image: url('{{obj.cover}}'); 
      background-size: cover; 
      background-repeat: no-repeat;
      background-color: gray;
      background-blend-mode: multiply;
      background-position: center center;
   
    }
</style>
{% endblock css %}
{% block title %}{{obj.title}} | Detail{% endblock title %}
{% block main %}
<div class="container ">
    <div class="col-xl-12 ">
      <div class="row justify-content-center">
        <div class="card mb-3 mt-5 p-3"  style="">
          <div class="row g-0 ">
            <div class="col-md-3" >
                <img src="{{obj.cover}}" height="450" width="300" id="image_src" alt="..." crossorigin="anonymous">
              </div>
            <div class="col-md-9">
              <div class="card-body " >
                <h2 class="text-light " > <strong>{{obj.title}}</strong> {{obj.year}}</h2>
                <p class="text-muted">{% if obj.certification %}<span class="border border-secondary p-1" >{{obj.certification}}</span>  {% endif %}{{obj.genre}}</p>
                
                {% if obj.relevance %}
                <p class="text-light">Relevance <span class="text-muted">{{obj.relevance}}%</span></p>
                {% endif %}
                  
                <div class="summary">
                    <h5 class="text-light ">Summary</h5>
                    <p class="card-text text-light">{{obj.summary}}</p>
                </div>
                {% if 'youtube' in obj.url and not 'embed' in obj.url %}
                <div class="trailer mt-3">
                    <a href="{{obj.url}}" class=" text-decoration-none" data-lightbox style="color: #cc5353;"><span><i class="fa fa-play" aria-hidden="true"></i></span> Watch Movie</a>
                </div>
                
                {% else %}
                <div class="trailer mt-3">
                    <a href="" class=" text-decoration-none" data-bs-toggle="modal" data-bs-target="#videoModal" style="color: #cc5353;"><span><i class="fa fa-play" aria-hidden="true"></i></span> Watch Movie</a>
                  </div>
                {% endif %}
                {% if obj.cast %}
                <div class="cast mt-3">
                    <h5 class="text-light">Cast</h5>
                    <p class="text-muted">
                        {{obj.cast}}
                    </p>
                </div>
                {% endif %} 
              </div>
            </div>
          </div>
        </div>
      </div>
       
    </div>
</div>


  
  <!-- Modal -->
  <div class="modal fade" id="videoModal" tabindex="-1" aria-labelledby="videoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg bg-transparent">
      <div class="modal-content bg-transparent">
        <div class="d-flex justify-content-md-center text-center">
          
          {% if 'iframe' in obj.url %}
            {{obj.url|safe}}
          {% else %}
          <video
                id="my-video"
                class="video-js video-js-responsive-container"
                controls
                autoplay
                preload="auto"
                width="640"
                height="480"
                poster="{{obj.cover}}"
                data-setup="{}">
                
            </video>
          {% endif %}
            
            
        </div>
      </div>
    </div>
  </div>
{% endblock main %}
{% block js %}
<script src="{% static 'js/videojs-playlist.js'%}"></script>
<script src="https://vjs.zencdn.net/7.7.5/video.js"></script>

    <script>
        const videoPlayer = document.getElementById("my-video")
        const videoModal = document.getElementById("videoModal")
        videoModal.addEventListener('hidden.bs.modal', function(){
            video.pause()
        })


        const videoList = [{{obj.url|safe}}]
        
        const video = videojs(document.getElementById("my-video"),{
          inactivityTimeout:0
        })
        try{
          video.volume(1);
        }
        catch (e){}

        video.on([
        'duringplaylistchange',
        'playlistchange',
        'beforeplaylistitem',
        'playlistitem',
        // 'playlistsorted', para rodar aleatoriamente
        ], function (e) {
          videojs.log('player saw "' + e.type + '"')
          // video.playlist.shuffle({rest:true})
          // video.playlist.autoadvance(0)
          video.playlist.nextButton(true)
        })
        
        video.playlist(videoList)
       
    </script>
{% endblock js %}

Fletnix/apps/movies/templates/movie_info.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
    .card{
        background-color: rgba(0,0,0,0.5);
    }
</style>
{% endblock css %}
{% block title %} {{res.title}} | Info{% endblock title %}
{% block main %}
<div class="container justify-content-md-center">
    <div class="col-xl-12">
        <div class="card mb-3 mt-5 p-3"  >
          <div class="row g-0">
            <div class="col-md-3" >
              <img src="{%if res.img%}{{res.img}}{%else%}{%static 'img/no-image.png'%}{%endif%}" height="450" width="300" id="image_src" alt="..." crossorigin="anonymous">
              <canvas id="canvas" hidden></canvas>
            </div>
            <div class="col-md-9 ">
              <div class="card-body " >
                <h2 class="text-light " id="movie_title"> <strong>{{res.title}}</strong> {{res.year}}</h2>
                <p class="text-muted"><span class="border border-secondary p-1" >{% if res.certification %}{{res.certification}}{% endif %}</span>{% for item in res.genre %}{{item}}{% if not forloop.last %},{% endif %}{%endfor%}</p>
                <p class="text-light">Relevance <span class="text-muted">{{res.relevance}}%</span></p>
                <div class="summary">
                    <h5 class="text-light ">Summary</h5>
                    <p class="card-text text-light">{{res.summary}}</p>
                </div>
                {% if res.trailer %}
                <div class="trailer mt-3">
                    <a href="https://www.youtube.com/watch?v={{res.trailer}}" class=" text-decoration-none" data-lightbox style="color: #cc5353;"><span><i class="fa fa-play" aria-hidden="true"></i></span> Watch Trailer</a>
                </div>
                {% endif %}
                {% if res.actors %}
                <div class="cast mt-3">
                    <h5 class="text-light">Cast</h5>
                    <p class="text-muted">
                        {% for item in res.actors  %}{{item}}{% if not forloop.last %}, {% endif %}{% endfor %}
                    </p>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          <form action="{%url 'movies:add'%}" method="post" enctype="multipart/form-data" id="movie-form">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" hidden id="id_title" name="title" value="{{res.title}}" >
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="id_summary" hidden name="summary"rows="2">{{res.summary}}</textarea>
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="id_trailer" hidden name="trailer"rows="2"> 
                    {% if not res.trailer %}https://www.youtube.com/watch?v=trailer{% else %}{{res.trailer}}{% endif %}
                </textarea>
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="id_cast" hidden name="cast"rows="2">{% for item in res.actors  %}{{item}}{% if not forloop.last %}, {% endif %}{% endfor %}</textarea>
            </div>
            <div class="mb-3">
                <input type="text" class="form-control" hidden id="id_year" value="{{res.year}}"name="year" >
            </div>
            <div class="mb-3">
                <input type="text" class="form-control" hidden id="id_genre" value="{% for item in res.genre %}{{item}}, {%endfor%}" name="genre" >
                <input type="text" class="form-control" hidden id="id_relevance" value="{{res.relevance}}" name="relevance" >
                <input type="text" class="form-control" hidden id="id_certification" value="{{res.certification}}" name="certification" >
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="id_cover" hidden name="cover" hidden rows="2" ></textarea>
            </div>
            <div class="mb-3">
                <label for="id_url" class="form-label text-light">URL</label>
                <textarea class="form-control bg-dark text-light" id="id_url" autofocus name="url"rows="1"></textarea>
            </div>
            <!-- <div class="mb-3">
              
                <input type="file" class="form-control"  id="id_file" hidden name="image">
            </div> -->
            <button class="btn btn-outline-success" type="submit">Save to Library</button>
        </form>
        </div>
    </div>
</div>
{% endblock main %}
{% block js %}
<script>
image_url = document.getElementById("image_src")
console.log(image_url)
cover = document.getElementById("id_cover")
canvas = document.getElementById('canvas')
var width = image_url.width 
var height = image_url.height

function clearphoto() {
  var context = canvas.getContext('2d');
  context.fillStyle = "#AAA";
  context.fillRect(0, 0, canvas.width, canvas.height);
  var data = canvas.toDataURL('image/png');
  cover.setAttribute('src', data);
  
}
function takepicture(){
    var context = canvas.getContext('2d');
    
    if (width && height) {
        canvas.width = width;
        canvas.height = height;
        context.drawImage(image_url, 0, 0, width, height);
        var data = canvas.toDataURL('image/jpg');
        // cover.innerHTML = data
        cover.innerHTML = image_url.src
        const movie_title = document.getElementById("movie_title").innerText
        
        var preview = document.getElementById('image_src');
        var file = document.getElementById('id_file') 

    } 
    else {
        clearphoto();
        }

        return data;
    }
    window.addEventListener("load", takepicture, false)


   
</script>
{% endblock js %}

Fletnix/apps/movies/templates/search_movie.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search{% endblock title %}
{% block main %}
<div class="container-fluid">
  {% include 'includes/_messages.html' %}
</div>
    <div class="container" id="movie-search">
        <div class="col-xl-12 mt-5">
            <form class="d-flex mt-3" method="POST" action="{% url 'movies:searcher' %}">
                {% csrf_token %}
              <input  class="form-control mr-2 text-white" id="movie-searcher" autofocus type="search" style="background-color:#18191c;" 
              name="search" autocomplete="off" placeholder="Search" aria-label="Search">
              <button class="btn text-white" style="background-color:#cc5353"type="submit">Search</button>
            </form>
        </div>
    </div>
    <div class="container" >
        <div class=" col-xl-12"  >
          <div class="row mt-3 justify-content-center">
            {% if res %}
            {% for item in res %}
            <div class="col-md-8">
              <a class="text-light text-decoration-none" href="{% url 'movies:info' forloop.counter %}" >
                <div class="card mb-2 bg-dark" >
                  <div class="col-lg-12 col-md-12 ">
                    <div class="row g-0 ">
                      <div class="col-lg-2 col-md-3 col-sm-3 mt-1 mb-1 text-center" >
                        {% if 'None' in item.image %}
                          <img src="{%static 'img/no-image.png'%}" alt="" style="width:94px;height:141px">
                        {% else %}
                        <img src="{{item.image}}" alt="" style="width:94px;height:141px" crossorigin="anonymous">
                        {% endif %}
                      </div>
                      <div class="col-lg-10 col-md-9 col-sm-9">
                        <div class="card-body " >
                          <h5 class="card-title text-left" >{{item.text}}</h5>
                          <p class="card-text">{{item.summary}}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                </div>
              </a>
            </div>
            {% endfor %}
            {%endif%}
          </div>
        </div>
      </div>
{% endblock main %}
robot